apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: sfp-portal
type: Opaque
stringData:
  # DO NOT COMMIT THIS FILE WITH ACTUAL VALUES
  # Use: kubectl create secret generic postgres-credentials ... (see guide)
  # OR use Sealed Secrets (recommended, see DIGITALOCEAN_SECURE_DEPLOYMENT.md)
  POSTGRES_USER: "doadmin"
  POSTGRES_PASSWORD: "CHANGE_ME_OR_USE_SEALED_SECRETS"
  POSTGRES_HOST: "db-xxxxx.ondigitalocean.com"
  POSTGRES_PORT: "25060"
  POSTGRES_DB: "sfp_portal"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: sfp-portal
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_GENERATE_WITH_OPENSSL"
  SENDGRID_API_KEY: "SG.optional"
