apiVersion: v1
kind: Pod
metadata:
  name: api-migrate-once
  namespace: sfp-portal
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: regcred
  containers:
    - name: api-migrate
      image: registry.digitalocean.com/sfp-portal/api:latest
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: postgres-credentials
        - secretRef:
            name: app-secrets
      env:
        - name: DB_SSL
          value: "true"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
      command: ["node"]
      args: ["src/migrations/runMigrations.js"]
---
apiVersion: v1
kind: Pod
metadata:
  name: api-seed-animals
  namespace: sfp-portal
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: regcred
  containers:
    - name: api-seed-animals
      image: registry.digitalocean.com/sfp-portal/api:latest
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: postgres-credentials
        - secretRef:
            name: app-secrets
      env:
        - name: DB_SSL
          value: "true"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
      command: ["node"]
      args: ["src/seeds/seedAnimals.js"]
---
apiVersion: v1
kind: Pod
metadata:
  name: api-seed-volunteers
  namespace: sfp-portal
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: regcred
  containers:
    - name: api-seed-volunteers
      image: registry.digitalocean.com/sfp-portal/api:latest
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: postgres-credentials
        - secretRef:
            name: app-secrets
      env:
        - name: DB_SSL
          value: "true"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
      command: ["node"]
      args: ["src/seeds/seedVolunteers.js"]
---
apiVersion: v1
kind: Pod
metadata:
  name: api-seed-applications
  namespace: sfp-portal
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: regcred
  containers:
    - name: api-seed-applications
      image: registry.digitalocean.com/sfp-portal/api:latest
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: postgres-credentials
        - secretRef:
            name: app-secrets
      env:
        - name: DB_SSL
          value: "true"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
      command: ["node"]
      args: ["src/seeds/seedApplications.js"]
