apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-monitor
  namespace: sfp-portal
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-monitor
  namespace: sfp-portal
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

---
# PrometheusRule for API alerts - Production Thresholds
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-alerts
  namespace: sfp-portal
  labels:
    app: api
spec:
  groups:
    - name: api-production-rules
      interval: 30s
      rules:
        # Error Rate Alert: >5% in 2 minutes
        - alert: APIHighErrorRate
          expr: |
            sum(rate(http_requests_total{status_code=~"5.."}[2m])) 
            / 
            sum(rate(http_requests_total[2m])) > 0.05
          for: 2m
          labels:
            severity: critical
            team: backend
          annotations:
            summary: "API error rate exceeds 5%"
            description: "Error rate is {{ $value | humanizePercentage }} (threshold: >5%)"

        # CPU Usage Alert: >80% for 5 minutes
        - alert: APIHighCPUUsage
          expr: |
            sum(rate(container_cpu_usage_seconds_total{pod=~"api-.*"}[5m])) * 100 > 80
          for: 5m
          labels:
            severity: critical
            team: backend
          annotations:
            summary: "API CPU usage exceeds 80%"
            description: "CPU usage is {{ $value | humanize }}% (threshold: >80%)"

        # Memory Usage Alert: >75% for 10 minutes
        - alert: APIHighMemoryUsage
          expr: |
            sum(container_memory_usage_bytes{pod=~"api-.*"}) / (256 * 1024 * 1024) * 100 > 75
          for: 10m
          labels:
            severity: warning
            team: backend
          annotations:
            summary: "API memory usage exceeds 75%"
            description: "Memory usage is {{ $value | humanize }}% (threshold: >75%)"

        # Latency Alert: P95 latency >500ms for 5 minutes
        - alert: APIHighLatencyP95
          expr: |
            histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.5
          for: 5m
          labels:
            severity: warning
            team: backend
          annotations:
            summary: "API P95 latency exceeds 500ms"
            description: "P95 latency is {{ $value | humanizeDuration }} (threshold: >500ms)"

        # Request Rate Spike Alert: >300% of baseline RPS
        - alert: APIHighRequestRateSpike
          expr: |
            abs(rate(http_requests_total[1m]) - rate(http_requests_total[5m])) 
            / 
            rate(http_requests_total[5m]) > 3.0
          for: 2m
          labels:
            severity: warning
            team: backend
          annotations:
            summary: "API request rate spike detected (>300%)"
            description: "RPS change is {{ $value | humanizePercentage }} (threshold: >300%)"

        # Pod Down Alert: any pod unreachable for 2 minutes
        - alert: APIPodDown
          expr: up{pod=~"api-.*"} == 0
          for: 2m
          labels:
            severity: critical
            team: backend
          annotations:
            summary: "API pod is down"
            description: "Pod {{ $labels.pod }} is not responding for 2 minutes"
